import requests 
from bs4 import BeautifulSoup
  
# api-endpoint 
URL = "https://servicios.igssgt.org/Servicios/Afiliados/ConsultaContribuciones.aspx"
  
# defining a params dict for the parameters to be sent to the API 
PARAMS = {
            '__EVENTTARGET':'ctl00$content$gridPatronos',
            '__EVENTARGUMENT':'Detalle$0',
            '__VIEWSTATE':'/wEPDwUJMTc3NzQ3MzIzD2QWAmYPZBYCAgMPZBYEAgcPZBYGAgEPZBYGAgEPDxYCHgRUZXh0ZWRkAg0PEA9kFgIeCG9uQ2hhbmdlBRFWZXJPcmRlbkNlZCh0aGlzKWRkZAIVDw8WAh4HRW5hYmxlZGhkZAIDDw8WAh4HVmlzaWJsZWdkFgQCAw8PFgIfAAUhT1JURUdBIFJFVk9MT1JJTyBNQVJMT04gQUxFWEFOREVSZGQCCQ88KwANAgAPFgQeC18hRGF0YUJvdW5kZx4LXyFJdGVtQ291bnQCBWQBEBYCZgIDFgI8KwAFAQAWAh4KSGVhZGVyVGV4dAUQTsO6bWVybyBwYXRyb25hbDwrAAUBABYCHwYFEFJhesOzbiBDb21lcmNpYWwWAmZmFgJmD2QWDmYPZBYCAgEPDxYCHwNoZGQCAQ9kFghmDw8WAh8ABQU0ODEyMWRkAgEPDxYEHwAFMkNBTi1BTSBDRU5UUk9BTUVSSUNBTkEgU09DSUVEQUQgQU5PTklNQSAgICAgICAgICAgHwNoZGQCAg8PFgIfAAUyQ0FOLUFNIENFTlRST0FNRVJJQ0FOQSBTT0NJRURBRCBBTk9OSU1BICAgICAgICAgICBkZAIDDw8WAh8ABSdDQU4tQU0gQ0VOVFJPQU1FUklDQU5BIFNPQ0lFREFEIEFOT05JTUFkZAICD2QWCGYPDxYCHwAFBTYwNzE2ZGQCAQ8PFgQfAAVQQ09OU09MSURBRE9TIE9DSE9DSUVOVE9TIFNJRVRFLCBTT0NJRURBRCBBTk9OSU1BICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAfA2hkZAICDw8WAh8ABVBDT05TT0xJREFET1MgT0NIT0NJRU5UT1MgU0lFVEUsIFNPQ0lFREFEIEFOT05JTUEgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRkAgMPDxYCHwAFEENPTlNPTElEQURPUyA4MDdkZAIDD2QWCGYPDxYCHwAFBjEzNzQ1OGRkAgEPDxYEHwAFUERST0dVRVJJQSBDRU5UUk8gSElTVE9SSUNPLCBTT0NJRURBRCBBTk9OSU1BICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgHwNoZGQCAg8PFgIfAAVQRFJPR1VFUklBIENFTlRSTyBISVNUT1JJQ08sIFNPQ0lFREFEIEFOT05JTUEgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkZAIDDw8WAh8ABRpEUk9HVUVSSUEgQ0VOVFJPIEhJU1RPUklDT2RkAgQPZBYIZg8PFgIfAAUGMTQ5Njk3ZGQCAQ8PFgQfAAVRRU1QTEVBRE9TIERFIFZBTkdVQVJESUEsIFNPQ0lFREFEIEFOw5NOSU1BICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgHwNoZGQCAg8PFgIfAAVRRU1QTEVBRE9TIERFIFZBTkdVQVJESUEsIFNPQ0lFREFEIEFOw5NOSU1BICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGQCAw8PFgIfAAUGRU1ERVZBZGQCBQ9kFghmDw8WAh8ABQYxMTE4NDFkZAIBDw8WBB8ABTJGQVJNQUNJQVMgR0FMRU5PLCBTT0NJRURBRCBBTk9OSU1BICAgICAgICAgICAgICAgIB8DaGRkAgIPDxYCHwAFMkZBUk1BQ0lBUyBHQUxFTk8sIFNPQ0lFREFEIEFOT05JTUEgICAgICAgICAgICAgICAgZGQCAw8PFgIfAAURRkFSTUFDSUEgR0FMRU5PIElkZAIGDw8WAh8DaGRkAgUPZBYCAgMPPCsADQBkAgkPZBYCAgEPDxYEHwAFDENvbnTDoWN0ZW5vcx4LTmF2aWdhdGVVcmwFVC9Db250YWN0ZW5vcy5hc3B4P0VtYWlsU29wb3J0ZT1TR2YyY1MxazREMCUzZC1jMjl3YjNKMFpYQnNZVzVwYkd4aFFHbG5jM05uZEM1dmNtYyUzZGRkGAIFGWN0bDAwJGNvbnRlbnQkZ3JpZERldGFsbGUPZ2QFGmN0bDAwJGNvbnRlbnQkZ3JpZFBhdHJvbm9zDzwrAAoBCAIBZI9Y1cmF2C4Ne2x0dYZGQ/qvDJ6V',
            '__VIEWSTATEGENERATOR':'1AA4A008',
            '__EVENTVALIDATION':'/wEWIwLzgOLXDwLVk5euAwKDmavkCQKXm9eRAgK6m+uPAgKE3MfoBQK+xaXDDwLYroreCQLyl+ioBALs+M6DDgKG4qyeCAKgy7LpAgK6ofK3CgLUitCCBAKQ6+WdCwKK3MvoBQKkxanDDwLero7eCQL4l+yoBAKA+PKDDgKN4tCeCALXy7bpAgKhofa3CgLbitSCBAKX6+mdCwKx3M/oBQKrxa3DDwKw29M3AsiRlIEGAqH05N8MAvSZhu4KAvWZhu4KAvaZhu4KAveZhu4KAuiZhu4KSaB4xP14fDaX6ePpXrtqNEmDe7k=',
            'ctl00$content$txtNumAfiliado':'22710239801011',
            'ctl00$content$ddlDocumentos':'DPI',
            'ctl00$content$ddlOrdenCedula':'A01',
            'ctl00$content$txtDocumento':'22710239801011',
            'ctl00$content$btnConsultar':'Consultar'
        } 
  
# sending get request and saving the response as response object
r = requests.post(url = URL, params = PARAMS) 
  
# extracting data in json format 
# data = r.text() 

# print(data)

soup = BeautifulSoup(r.text, 'html.parser')
print(soup.prettify())